[#dmn-invocation-rest-proc]
= Calling a DMN service on a remote server using REST APIs

This section explains how to interact with a KIE Container from any client type using the REST endpoints. The examples here demonstrate using *nix style "curl" commands but provide relevant information to adapt to any Rest client.

.Prerequisites

* KIE Execution Server installed and configured, including service user accounts to allow access.
* A KIE Container deployed in the KIE Execution Server in the form of a KJAR that includes the DMN model.
* Knowing the container ID of the KIE Container containing the DMN model. If using more than one model, you must also know the model namespace and model name of the specific model being invoked.

.Procedure
. Determine base URL for accessing the Rest endpoints. This requires knowing the following values (with the default local deployment values as an example):

* Host (localhost)
* Port (8080)
* Root context (kie-server)
* Base Rest path (services/rest/server)

Local deployment example URL:
[source]
----
http://localhost:8080/kie-server/services/rest/server
----

. Determine user authentication needs.

When users are defined directly in the KIE Execution server configuration, BasicAuth is used which requires the username and password.  Successful requests require that the user have the "kie-server" role.

Example curl request with credentials:
[source]
----
curl -u username:password <request>
----

If the KIE Execution server is configured with KeyCloak, the request must include a Bearer Token:
[source,java]
----
curl -H "Authorization: bearer $TOKEN" <request>
----

. Specify the format of the request and/or response.

The Rest endpoints work with both JSON and XML formats and are set using request headers:

.Header parameters to specify JSON format:
[source]
----
curl -H "accept: application/json" -H "content-type: application/json"
----

.Header parameters to specify XML format:
[source]
----
curl -H "accept: application/xml" -H "content-type: application/xml"
----

. (Optional) Query the container for a list of deployed decision models.
*[GET]* /containers/$containerId/dmn

Putting it altogether for a local install with the Age Classification sample:
[source]
----
curl -u krisv:krisv -H "accept: application/xml" -X GET "http://localhost:8080/kie-server/services/rest/server/containers/MovieDMNContainer/dmn"
----

Sample XML output:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<response type="SUCCESS" msg="OK models successfully retrieved from container 'MovieDMNContainer'">
    <dmn-model-info-list>
        <model>
            <model-namespace>http://www.redhat.com/_c7328033-c355-43cd-b616-0aceef80e52a</model-namespace>
            <model-name>dmn-movieticket-ageclassification</model-name>
            <model-id>_99</model-id>
            <decisions>
                <dmn-decision-info>
                    <decision-id>_3</decision-id>
                    <decision-name>AgeClassification</decision-name>
                </dmn-decision-info>
            </decisions>
        </model>
    </dmn-model-info-list>
</response>
----

Sample JSON output:
[source,json]
----
{
  "type" : "SUCCESS",
  "msg" : "OK models successfully retrieved from container 'MovieDMNContainer'",
  "result" : {
    "dmn-model-info-list" : {
      "models" : [ {
        "model-namespace" : "http://www.redhat.com/_c7328033-c355-43cd-b616-0aceef80e52a",
        "model-name" : "dmn-movieticket-ageclassification",
        "model-id" : "_99",
        "decisions" : [ {
          "decision-id" : "_3",
          "decision-name" : "AgeClassification"
        } ]
      } ]
    }
  }
}
----

. Executing the model

*[POST]* /containers/$containerId/dmn

Putting it all together for a local install with the Age Classification sample:
[source]
----
curl -u krisv:krisv -H "accept: application/json" -H "content-type: application/json" -X POST "http://localhost:8080/kie-server/services/rest/server/containers/MovieDMNContainer/dmn" -d "{ \"model-namespace\" : \"http://www.redhat.com/_c7328033-c355-43cd-b616-0aceef80e52a\", \"model-name\" : \"dmn-movieticket-ageclassification\", \"decision-name\" : [ ], \"decision-id\" : [ ], \"dmn-context\" : {\"Age\" : 66}}"
----

.Formatted JSON request:
[source,json]
----
{
  "model-namespace" : "http://www.redhat.com/_c7328033-c355-43cd-b616-0aceef80e52a",
  "model-name" : "dmn-movieticket-ageclassification",
  "decision-name" : [ ],
  "decision-id" : [ ],
  "dmn-context" : {"Age" : 66}
}
----

.Formatted XML request (JAXB style):
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<dmn-evaluation-context>
    <model-namespace>http://www.redhat.com/_c7328033-c355-43cd-b616-0aceef80e52a</model-namespace>
    <model-name>dmn-movieticket-ageclassification</model-name>
    <dmn-context xsi:type="jaxbListWrapper" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <type>MAP</type>
        <element xsi:type="jaxbStringObjectPair" key="Age">
            <value xsi:type="xs:int" xmlns:xs="http://www.w3.org/2001/XMLSchema">66</value>
        </element>
    </dmn-context>
</dmn-evaluation-context>
----

Regardless of format, the request requires:
* Model namespace
* Model name
* Context object containing input values

.Example JSON response:
[source,json]
----
{
  "type" : "SUCCESS",
  "msg" : "OK from container 'MovieDMNContainer'",
  "result" : {
    "dmn-evaluation-result" : {
      "messages" : [ ],
      "model-namespace" : "http://www.redhat.com/_c7328033-c355-43cd-b616-0aceef80e52a",
      "model-name" : "dmn-movieticket-ageclassification",
      "decision-name" : [ ],
      "dmn-context" : {
        "Age" : 66,
        "AgeClassification" : "Senior"
      },
      "decision-results" : {
        "_3" : {
          "messages" : [ ],
          "decision-id" : "_3",
          "decision-name" : "AgeClassification",
          "result" : "Senior",
          "status" : "SUCCEEDED"
        }
      }
    }
  }
}
----

.Example XML (JAXB format) response:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<response type="SUCCESS" msg="OK from container 'MovieDMNContainer'">
      <dmn-evaluation-result>
            <model-namespace>http://www.redhat.com/_c7328033-c355-43cd-b616-0aceef80e52a</model-namespace>
            <model-name>dmn-movieticket-ageclassification</model-name>
            <dmn-context xsi:type="jaxbListWrapper" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                  <type>MAP</type>
                  <element xsi:type="jaxbStringObjectPair" key="Age">
                        <value xsi:type="xs:int" xmlns:xs="http://www.w3.org/2001/XMLSchema">66</value>
                  </element>
                  <element xsi:type="jaxbStringObjectPair" key="AgeClassification">
                        <value xsi:type="xs:string" xmlns:xs="http://www.w3.org/2001/XMLSchema">Senior</value>
                  </element>
            </dmn-context>
            <messages/>
            <decisionResults>
                  <entry>
                        <key>_3</key>
                        <value>
                              <decision-id>_3</decision-id>
                              <decision-name>AgeClassification</decision-name>
                              <result xsi:type="xs:string" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">Senior</result>
                              <messages/>
                              <status>SUCCEEDED</status>
                        </value>
                  </entry>
            </decisionResults>
      </dmn-evaluation-result>
</response>
----
